Pull project-related changes from fst3a/feature/impl-file
nyxxxie/spade pull request #25
Opened 2017-02-07 14:50 UTC by fst3a

2017-02-07 15:05 UTC, nyxxxie commented on spade/core/project.py
> +        metadata = MetaData()
When are these vars ever used?

2017-02-07 15:09 UTC, nyxxxie commented on spade/core/project.py
> +SCHEMA_VERSION = "0.0a"
You define this var but then never use it (it should be used in constructor where we set schema version project info variable).  Also I don't want to use a strict versioning system with major and minor changes for this, lets just use a nonce and up the number each time we change the schema.

2017-02-07 15:11 UTC, nyxxxie commented on spade/core/project.py
> +    def db(self):
We never define a _db object, I instead have a function db_engine() that returns the sqlalchemy engine.

2017-02-07 15:16 UTC, nyxxxie commented on spade/core/project.py
> +        # FIXME(fst3a): This is plain wrong, one project can have multiple files
If you're undecided on how this feature should function, perhaps we should just make it a seperate feature and merge it when it is ready?  I don't like large amounts of commented out code accompanied by a large FIXME comment just sitting in code that might be merged soon.

2017-02-07 15:17 UTC, nyxxxie requested changes
Left comments, check them out and comment or address them

2017-02-07 15:36 UTC, fst3a commented on spade/core/project.py
> +        metadata = MetaData()
whops, they aren't, forgot to remove

2017-02-07 15:37 UTC, fst3a commented on spade/core/project.py
> +SCHEMA_VERSION = "0.0a"
It is a constant, not a variable.  It should be inserted in project_info on new db or upgrade.

2017-02-07 15:37 UTC, fst3a commented on spade/core/project.py
> +    def db(self):
Ok.

2017-02-07 15:37 UTC, fst3a commented on spade/core/project.py
> +        # FIXME(fst3a): This is plain wrong, one project can have multiple files
Ok.

2017-02-09 19:56 UTC, nyxxxie commented on spade/core/project.py
>          self.__add_info("creation_datetime", date, True)
Missed a spot :^)

2017-02-09 19:58 UTC, fst3a commented on spade/core/project.py
>          self.__add_info("creation_datetime", date, True)
fucking cia nigger

2017-02-09 20:44 UTC, nyxxxie approved these changes
Looks good

2017-02-09 20:44 UTC, merged